name: Auto Code Deployment

on:
  push:
    branches:
      - main

jobs:
  production-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SECRET_KEY }}
          debug: true
          script: |
            echo "Go To Project Directory"
            cd rmw_chatbot

            echo "Take Pull From Main Branch"
            git pull origin main


            echo "Activate env"
            python3 -m venv venv
            ./venv/bin/pip install -r requirements.txt

            echo "Install dependencies"
            pip install -r requirements.txt

            echo "Restart PM2"
            pm2 restart chatbot